apiVersion: v1
kind: Pod
metadata:
  name: mariadb-pod
spec:
  containers:
  - name: mariadb
    image: mariadb:latest
    env:
    - name: MARIADB_ROOT_PASSWORD
      value: "rootpassword"  # You can replace this with your desired password
  nodeSelector:
    kubernetes.io/hostname: gke-cluster-1-default-pool-63542052-w1m0
