apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  containers:
  - name: mysql
    image: mysql:latest
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "rootpassword"  # You can replace this with your desired password
  nodeSelector:
    kubernetes.io/hostname: gke-cluster-1-default-pool-63542052-pk4b

